<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mayuresh" failures="1" tests="5" name="GlobalVariablesValidationDemo" time="27.217" errors="0" timestamp="2025-01-09T07:47:24 IST">
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSubmission" time="2.629"/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSubmission" time="2.636"/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSummary" time="1.234"/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderFailureDemo" time="1.017">
    <skipped/>
  </testcase> <!-- validateOrderFailureDemo -->
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderFailureDemo" time="1.921">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap.validateOrderFailureDemo(ProductCatalogueHashMap.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- validateOrderFailureDemo -->
</testsuite> <!-- GlobalVariablesValidationDemo -->
